AWSTemplateFormatVersion: '2010-09-09'
Resources:
  BootstrapBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: '<default-bootstrap-bucket-name>'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: '<default-log-bucket-name>'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  SilverBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: '<default-silver-bucket-name>'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  GoldBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: '<default-gold-bucket-name>'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  KafkaServersParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: bootstrap-servers
      Type: String
      Value: 'boot-XXXXXXXX.c1.kafka-serverless.eu-central-1.amazonaws.com:9098'

  KafkaTopicsParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: read-topic
      Type: String
      Value: 'solar.segment.01'

  SnsTopicParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: sns-topic
      Type: String
      Value: '<your-sns-topic-arn>'

  EmrAppIdParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: emr-app-id
      Type: String
      Value: '<your-emr-app-id>'

  BootstrapBucketParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: 'bootstrap-bucket'
      Type: String
      Value: !Ref BootstrapBucket

  LogBucketParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: 'log-bucket'
      Type: String
      Value: !Ref LogBucket

  SilverBucketParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: 'silver-bucket'
      Type: String
      Value: !Ref SilverBucket

  GoldBucketParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: 'gold-bucket'
      Type: String
      Value: !Ref GoldBucket

Outputs:
  KafkaServersParameterName:
    Description: 'The name of the Parameter Store entry for the Kafka servers'
    Value: !Ref KafkaServersParam

  KafkaTopicsParameterName:
    Description: 'The name of the Parameter Store entry for the Kafka topics'
    Value: !Ref KafkaTopicsParam

  SnsTopicParameterName:
    Description: 'The name of the Parameter Store entry for the SNS topic ARN'
    Value: !Ref SnsTopicParam

  EmrAppIdParameterName:
    Description: 'The name of the Parameter Store entry for the EMR app ID'
    Value: !Ref EmrAppIdParam

  BootstrapBucketParameterName:
    Description: 'The name of the Parameter Store entry for the Bootstrap Bucket'
    Value: !Ref BootstrapBucketParam

  LogBucketParameterName:
    Description: 'The name of the Parameter Store entry for the Log Bucket'
    Value: !Ref LogBucketParam

  SilverBucketParameterName:
    Description: 'The name of the Parameter Store entry for the Silver Bucket'
    Value: !Ref SilverBucketParam

  GoldBucketParameterName:
    Description: 'The name of the Parameter Store entry for the Gold Bucket'
    Value: !Ref GoldBucketParam
